# -*- coding: utf-8 -*-
"""textBlob.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sVNKR3IxlcHq_wOZ3NeZAOMe39QVs1VO
"""

from PIL import Image

import nltk
import requests
from textblob import TextBlob
from io import BytesIO

#@title Enter Text Here
text = 'Old McDonald had a farm' #@param {type:"string"}
blob1 = TextBlob(text)
s_pol = blob1.sentiment.polarity
s_sub = blob1.sentiment.subjectivity
print(s_pol, s_sub)

#s_pol = -0.8

if s_pol <= -0.7:
  print("Statement is very Negative : " + str(s_pol))
  url = "https://www.itweb.co.za/static/pictures/2018/10/resized/-fs-dislike-emoji-2018.xl.jpg"
  response = requests.get(url)
  img = Image.open(BytesIO(response.content))
  img.show()
elif s_pol >= -0.69 and s_pol <= -0.25:
  print("Statement is Moderately Negative : " + str(s_pol))
  url = "https://image.shutterstock.com/image-vector/emoji-emoticon-grumpy-expression-260nw-1420797230.jpg"
  response = requests.get(url)
  img = Image.open(BytesIO(response.content))
  img.show()
elif s_pol >= -0.2 and s_pol <= 0.2:
  print("Statement is Neutral : " + str(s_pol))
  url = "https://cdn.shopify.com/s/files/1/1061/1924/products/Expressionless_Face_Emoji_grande.png?v=1571606037"
  response = requests.get(url)
  img = Image.open(BytesIO(response.content))
  img.show()
elif s_pol >= 0.25 and s_pol <= 0.69:
  print("Statement is Moderately Positive : " + str(s_pol))
  url = "https://cdn.shopify.com/s/files/1/1061/1924/products/Neutral_Face_Emoji_large.png?v=1571606037"
  response = requests.get(url)
  img = Image.open(BytesIO(response.content))
  img.show()
elif s_pol >= 0.7:
  print("Statement is very Positive : " + str(s_pol))
  url = "https://i.pinimg.com/originals/c0/1d/28/c01d28d4c27d214e5222413238b9bd89.jpg"
  response = requests.get(url)
  img = Image.open(BytesIO(response.content))
  img.show()

print(blob1.detect_language())

